//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfEmp
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeModel", Namespace="http://schemas.datacontract.org/2004/07/MyServices.Model")]
    public partial class EmployeeModel : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfEmp.ICrudService")]
    public interface ICrudService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/AddEmployee", ReplyAction="http://tempuri.org/ICrudService/AddEmployeeResponse")]
        void AddEmployee(WcfEmp.EmployeeModel emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/AddEmployee", ReplyAction="http://tempuri.org/ICrudService/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(WcfEmp.EmployeeModel emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/EditEmployee", ReplyAction="http://tempuri.org/ICrudService/EditEmployeeResponse")]
        void EditEmployee(WcfEmp.EmployeeModel emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/EditEmployee", ReplyAction="http://tempuri.org/ICrudService/EditEmployeeResponse")]
        System.Threading.Tasks.Task EditEmployeeAsync(WcfEmp.EmployeeModel emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/DeleteEmployee", ReplyAction="http://tempuri.org/ICrudService/DeleteEmployeeResponse")]
        WcfEmp.EmployeeModel DeleteEmployee(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/DeleteEmployee", ReplyAction="http://tempuri.org/ICrudService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<WcfEmp.EmployeeModel> DeleteEmployeeAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetEmployees", ReplyAction="http://tempuri.org/ICrudService/GetEmployeesResponse")]
        WcfEmp.EmployeeModel[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetEmployees", ReplyAction="http://tempuri.org/ICrudService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<WcfEmp.EmployeeModel[]> GetEmployeesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ICrudServiceChannel : WcfEmp.ICrudService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class CrudServiceClient : System.ServiceModel.ClientBase<WcfEmp.ICrudService>, WcfEmp.ICrudService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrudServiceClient() : 
                base(CrudServiceClient.GetDefaultBinding(), CrudServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrudService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CrudServiceClient.GetBindingForEndpoint(endpointConfiguration), CrudServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrudServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrudServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void AddEmployee(WcfEmp.EmployeeModel emp)
        {
            base.Channel.AddEmployee(emp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(WcfEmp.EmployeeModel emp)
        {
            return base.Channel.AddEmployeeAsync(emp);
        }
        
        public void EditEmployee(WcfEmp.EmployeeModel emp)
        {
            base.Channel.EditEmployee(emp);
        }
        
        public System.Threading.Tasks.Task EditEmployeeAsync(WcfEmp.EmployeeModel emp)
        {
            return base.Channel.EditEmployeeAsync(emp);
        }
        
        public WcfEmp.EmployeeModel DeleteEmployee(int Id)
        {
            return base.Channel.DeleteEmployee(Id);
        }
        
        public System.Threading.Tasks.Task<WcfEmp.EmployeeModel> DeleteEmployeeAsync(int Id)
        {
            return base.Channel.DeleteEmployeeAsync(Id);
        }
        
        public WcfEmp.EmployeeModel[] GetEmployees()
        {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<WcfEmp.EmployeeModel[]> GetEmployeesAsync()
        {
            return base.Channel.GetEmployeesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrudService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrudService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8090/MyServices/CrudService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrudServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrudService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrudServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrudService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrudService,
        }
    }
}
